#-------------------------------
# General Site Settings

title: KBDIO
description: LOGO Design, шо╛шоб
url: "https://kilbong0508.github.io" 


#-------------------------------
# About Section
author-name:   KB Choi
author-avatar: kb_avatar.jpg


#-------------------------------
# Contact links
 facebook:  https://facebook.com/ # Add your Facebook handle
 twitter:   https://twitter.com/ # Add your Facebook handle
 instagram: https://www.instagram.com/ # Add your Facebook handle
 pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
# instafeed: true 


#-------------------------------
# Google Analytics
google-analytics: 


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
